services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: payout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

  backend:
    build: ./payout-backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: ./payout-backend
    container_name: celery_worker
    command: celery -A core worker -l info
    depends_on:
      - backend
      - redis

  frontend:
    build: ./payout-frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: