# Generated by Django 6.0.4 on 2026-04-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='idempotencykey',
            name='payouts_ide_merchan_4d8fc8_idx',
        ),
    ]
